version: '3'
services:
  cassandra:
    image: scylladb/scylla:3.0.8
    volumes:
      - scylladb1:/var/lib/scylla
  cassandra2:
    image: scylladb/scylla:3.0.8
    command: --seeds=cassandra
    depends_on:
      - cassandra
    volumes:
      - .scylladb2:/var/lib/scylla
  cassandra3:
    image: scylladb/scylla:3.0.8
    command: --seeds=cassandra
    depends_on:
      - cassandra
    volumes:
      - scylladb3:/var/lib/scylla

  cassandra-schema:
    image: jaegertracing/jaeger-cassandra-schema:1.13.1
    depends_on:
      - cassandra
      - cassandra2
      - cassandra3

  jaeger-collector:
    image: jaegertracing/jaeger-collector:1.13.1
    command: ["--cassandra.keyspace=jaeger_v1_dc1", "--cassandra.servers=cassandra", "--collector.zipkin.http-port=9411"]
    ports:
      - "14269"
      - "14268:14268"
      - "14267"
      - "14250"
      - "9411:9411"
    restart: on-failure
    depends_on:
      - cassandra-schema

  jaeger-agent: 
    image: jaegertracing/jaeger-agent:1.13.1
    command: ["--reporter.grpc.host-port=jaeger-collector:14250"]
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
    restart: on-failure
    depends_on:
      - jaeger-collector

  jaeger-query:
    image: jaegertracing/jaeger-query:1.13.1
    command: ["--cassandra.keyspace=jaeger_v1_dc1", "--cassandra.servers=cassandra"]
    ports:
      - "16686:16686"
      - "16687"
    restart: on-failure
    depends_on:
      - cassandra-schema

volumes:
  scylladb1:
    driver: local
  scylladb2:
    driver: local
  scylladb3:
    driver: local
 